http:
  host: "0.0.0.0"
  port: "8081"
app:
  runtime: "4.4.0"
  
anypoint:
  username: "DevMax"
  password: "MuleMax2021"
    
cloudhub:
  app: "blueoceansh"
  workers: "1"
  workerType: "Micro"
  region: "US East, Ohio"
  bg: "SelfTaught"
  environment: "Sandbox"