http:
  host: "0.0.0.0"
  port: "8081"
  path: "/ocean"
mule:
  version: "4.4.0"
  
anypoint:
  username: "DevMax"
  password: "MuleMax2021"
    
cloudhub:
  app: "blueoceansh"
  workers: "1"
  worker: "Micro"
  region: "us-east-2"
  bg: "SelfTaught"
  environment: 
    - "Sandbox"
    - "Production"